---
title: "Data Analysis - Chess Tournament"
author: "Trang Do"
date: '`r Sys.Date()`'
output:
  rmdformats::robobook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Preparing Data from a provided CSV

This part reads data of players in CSV file to dataframe in R. It also unnecessary data from CSV file

Reading CSV and remove redundant data
```{r library}
library(dplyr)
library(stringr)

path <- "https://raw.githubusercontent.com/Trangmis/607/master/project1/tournamentinfo.txt"
txtfile <- read.csv(path, header = F, sep = "|")

txtfile <- txtfile %>% filter(!(str_detect(V1,"--|Num|Pair")))
```

## 2. Converting Data to data frame

** Initialize Data Frame
```{r initialize-data-frame}
players_frame <- data.frame(playerid=0,playername='',totalpoints=0,R=0,
                            averagepoint=0,predictedpoint=0,
                            r1_status='',r1_opponent=0,r2_status=0,r2_opponent=0,
                            r3_status='',r3_opponent=0,r4_status='',r4_opponent=0,
                            r5_status='',r5_opponent=0,r6_status='',r6_opponent=0,
                            r7_status='',r7_opponent=0)
players <- data.frame(playerid=0,playername='',totalpoints=0,r=0,
                            averagepoint=0,predictedpoint=0)
player_games <- data.frame(playerid=0, opponent=0,status='',round=0)
```


```{r}
oddrows <- txtfile %>% filter(row_number() %% 2 == 1) %>%
                      mutate(player = as.integer(V1),
                             playername = V2,
                             points = V3,
                             r1 = substr(V4,1,1), 
                             r1_opponent = as.integer(substr(V4,2,str_length(V4))),
                             r2 = substr(V5,1,1), 
                             r2_opponent = as.integer(substr(V5,2,str_length(V5))),
                             r3 = substr(V6,1,1), 
                             r3_opponent = as.integer(substr(V5,2,str_length(V6))),
                             r4 = substr(V7,1,1), 
                             r4_opponent = as.integer(substr(V5,2,str_length(V7))),
                             r5 = substr(V8,1,1), 
                             r5_opponent = as.integer(substr(V5,2,str_length(V8))),
                             r6 = substr(V9,1,1), 
                             r6_opponent = as.integer(substr(V5,2,str_length(V9))),
                             r7 = substr(V10,1,1), 
                             r7_opponent = as.integer(substr(V5,2,str_length(V10)))) 
    
evenrows <- txtfile %>% 
          filter(row_number() %% 2 == 0)%>%
          mutate(player = row_number(),
             uscf_id = as.integer(substr(V2,1,str_locate_all(pattern = " / R:", V2)[[1]][1])),
             startp = str_locate(pattern = ":", V2)[[1]][1]+1,
             end1 = str_locate(V2,"P")-1,
             end2 = str_locate(V2,">")-2
             )
evenrows$end1[is.na(evenrows$end1)] <- 0

evenrows <- evenrows %>%
                  mutate(pre_rating=as.integer(substr(V2,startp,ifelse(end1==0,end2,end1))))

evenrows <- evenrows %>% select (player,uscf_id , pre_rating)
oddrows <- oddrows %>% select (player,playername, points, r1,r1_opponent,
                                r2,r2_opponent, r3,r3_opponent,
                               r4,r4_opponent, r5,r5_opponent,
                               r6,r6_opponent, r7,r7_opponent)

df <- merge(evenrows,oddrows,by="player")
head(df)
```

## 3. PostgreSQL

## Writing data frame to PostgreSQL

```{r}
library(DBI)

db <- 'project1'  #provide the name of your db
host_db <- 'localhost'
db_port <- '5432'
db_user <- 'ass2' 
db_password <- 'data607'

con <- dbConnect(RPostgres::Postgres(), dbname = db, host=host_db, port=db_port, user=db_user, password=db_password) 

dbWriteTable(con, "df", df, overwrite = TRUE, row.names = FALSE)

sqlstatement<- "(select player, 1 as round ,r1 as status, r1_opponent as opponent
            from df) union
            (select player, 2 as round,r2 as status, r2_opponent as opponent
            from df) union
            (select player, 3 as round,r3 as status, r3_opponent as opponent
            from df) union
            (select player, 4 as round,r4 as status, r4_opponent as opponent
            from df) union
            (select player, 5 as round,r5 as status, r5_opponent as opponent
            from df) union
            (select player, 6 as round,r6 as status, r6_opponent as opponent
            from df) union
            (select player, 7 as round,r7 as status, r7_opponent as opponent
            from df)"

dbquery <- dbGetQuery(con,sqlstatement)

dbWriteTable(con, "df_games", dbquery, overwrite = TRUE, row.names = FALSE)

dbDisconnect(con)
```